id: tas-irmznurf
type: task
title: Dark mode
status: done
createdAt: 2026-02-19T19:41:41.299Z
updatedAt: 2026-02-19T19:59:02.343Z
description: Add dark mode to web ui
assignee: use-JTYCH2se
sprint: spr-hDifgOv0
priority: critical
estimate: 2
