id: tas-rMM9imow
type: task
title: Misleading sprint complete button
status: todo
createdAt: 2026-02-19T19:40:35.940Z
updatedAt: 2026-02-19T19:40:35.940Z
description: >-
  The green "Complete" button on the sprint UI looks too much like a tag that shows a complete status. Make it look more
  like a button and not a tag.
assignee: use-JTYCH2se
sprint: spr-hDifgOv0
priority: medium
estimate: 1
