id: tas-CQAh7pz-
type: task
title: Persist web ui settings
status: todo
createdAt: 2026-02-19T22:08:58.682Z
updatedAt: 2026-02-19T22:08:58.682Z
description: |-
  Last selected web ui options should be persisted locally (gitignored) 
  - dark mode
  - View mode
  - Filter by sprint
  - Last Filters
  - Last Search Term
assignee: use-JTYCH2se
sprint: spr-hDifgOv0
priority: medium
estimate: 3
