id: tas-6-1ZdYM2
type: task
title: A11y pass
status: todo
createdAt: 2026-02-19T20:58:08.972Z
updatedAt: 2026-02-19T20:58:08.972Z
description: Update web ui for accessibility standards
assignee: use-JTYCH2se
sprint: spr-hDifgOv0
priority: medium
estimate: 2
