id: tas-14eWaSjK
type: task
title: Add Kanban View
status: done
createdAt: 2026-02-19T21:06:12.696Z
updatedAt: 2026-02-19T22:09:57.404Z
description: add kanban | card toggle and kanban view for issues
assignee: use-JTYCH2se
sprint: spr-hDifgOv0
priority: medium
estimate: 4
